In [7]:
import pandas as pd
import gc
gcjs = []
for x in range(2008, 2020):
    gcjs.append(pd.read_csv(f"GCJ/gcj{x}.csv/gcj{x}.csv"))
gcjwhole = pd.concat(gcjs, ignore_index=True, copy=False)
gcjs.clear()
gc.collect()

C:\Users\timus\AppData\Local\Temp\ipykernel_98060\2309733987.py:5: DtypeWarning: Columns (0: round) have mixed types. Specify dtype option on import or set low_memory=False.
  gcjs.append(pd.read_csv(f"GCJ/gcj{x}.csv/gcj{x}.csv"))
C:\Users\timus\AppData\Local\Temp\ipykernel_98060\2309733987.py:6: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  gcjwhole = pd.concat(gcjs, ignore_index=True, copy=False)

1193

In [8]:
gcjwhole

,Unnamed: 0,year,round,username,task,solution,file,full_path,flines
0,0,2008,32002,MikeSeibert,24445,0,EndlessKnight.java,gcj/2008/32002/MikeSeibert/24445/0/extracted/E...,import java.util.Scanner;\n \n public class En...
1,1,2008,32002,MikeSeibert,24444,1,Pockets.java,gcj/2008/32002/MikeSeibert/24444/1/extracted/P...,import java.util.Scanner;\n \n public class Po...
2,2,2008,32002,MikeSeibert,24444,0,Pockets.java,gcj/2008/32002/MikeSeibert/24444/0/extracted/P...,import java.util.Scanner;\n \n public class Po...
3,3,2008,32002,MikeSeibert,24446,0,NoCheating.java,gcj/2008/32002/MikeSeibert/24446/0/extracted/N...,import java.util.Scanner;\n \n public class No...
4,4,2008,32002,bhamrick,24445,0,D.cpp,gcj/2008/32002/bhamrick/24445/0/extracted/D.cpp,#include<cstdio>\n #include<cstdlib>\n \n #def...
...,...,...,...,...,...,...,...,...,...
1924482,398175,2019,51705,isshyoboytarun,0000000000088231,00000000000b9534,00000000000b9534.PYTHON3,NaN,T=int(input())\nc=0\nfor x in range(T):\n N...
1924483,398176,2019,51705,isshyoboytarun,0000000000088231,00000000000b85e2,00000000000b85e2.PYTHON3,NaN,T=int(input())\n\nfor x in range(T):\n c=0\...
1924484,398177,2019,51705,isshyoboytarun,0000000000088231,00000000000b8458,00000000000b8458.PYTHON3,NaN,T=int(input())\n\nfor x in range(T):\n c=0\...
1924485,398178,2019,51705,MrAlien,0000000000088231,000000000008ab87,000000000008ab87.JAVA,NaN,import java.io.BufferedReader;\nimport java.io...
1924486,398179,2019,51705,MrAlien,0000000000088231,000000000008a851,000000000008a851.JAVA,NaN,import java.io.BufferedReader;\nimport java.io...

In [13]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("C:\\Users\\timus\Downloads\\gcj-archive-2023\\2023a\\raw_data.sqlar")

<>:4: SyntaxWarning: invalid escape sequence '\D'
<>:4: SyntaxWarning: invalid escape sequence '\D'
C:\Users\timus\AppData\Local\Temp\ipykernel_98060\3302027309.py:4: SyntaxWarning: invalid escape sequence '\D'
  conn = sqlite3.connect("C:\\Users\\timus\Downloads\\gcj-archive-2023\\2023a\\raw_data.sqlar")

In [14]:
df = pd.read_sql("SELECT * FROM sqlar", conn)

In [50]:
pd.set_option('display.max_rows', 30)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [52]:
df[82:90]

                                      name   mode       mtime    sz  \
82         raw_data/attempts/dbsic211.json  33206  1681617485  4443
83             raw_data/attempts/tabr.json  33206  1681617487  4442
84  raw_data/attempts/tmwilliamlin168.json  33206  1681617489  4443
85       raw_data/attempts/__declspec.json  33206  1681617489  4443
86         raw_data/attempts/xiaowuc1.json  33206  1681617490  5598
87        raw_data/attempts/aryanc403.json  33206  1681617491  4443
88        raw_data/attempts/IanDeHaan.json  33206  1681617492  4986
89            raw_data/attempts/Joshc.json  33206  1681617492  5613

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 data
82                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    b'{"attempts":[{"id":"0000000000cb3e0c","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U0fBLV1Uhq5dIEQkM7Obx0s5ekT2Ci1jDgV4MUQcpaJREv-_JCy/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c1","timestamp_ms":1681568229979.931},{"id":"0000000000cb2d13","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U3FjXpiFxFLXbQuV4Tn5G0BoW0uAFij929FJnwFkHWEoCI1mP2m/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c2","timestamp_ms":1681567969161.597},{"id":"0000000000cb24b8","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U1dIlZw8tY5kCHe13re77TiBQGpFR3InNPx2-sH29JNZjoStQyQ/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cada38","timestamp_ms":1681567787221.909},{"id":"0000000000cb1e76","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U0dx5MTP6vqKp2OJuAHj2otw6asJ40-i1tR5Snt_zqGTSFF1fSb/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad086","timestamp_ms":1681567642319.242},{"id":"0000000000cb1669","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U0PMGjJl4yLWDIPhUimsr1GpbS95yhuBUXTq6UI6NuRD5ZoIA41/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad7cf","timestamp_ms":1681567366367.667}],"challenge":{"announcements":[],"are_results_final":true,"end_ms":1681581600000,"id":"0000000000c95b94","is_practice_available":true,"result_status":30,"result_status__str":"FINALIZED","start_ms":1681567200000,"tasks":[{"id":"0000000000cad086","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Illumination Optimization"},{"id":"0000000000cad7cf","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Colliding Encoding"},{"id":"0000000000cad9c1","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"Untie"},{"id":"0000000000cad9c2","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"ASCII Art"},{"id":"0000000000cada38","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Rainbow Sort"}],"title":"Round A"}}\n'
83                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     b'{"attempts":[{"id":"0000000000cb38b1","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U3AfyK3jBCqErmXNP2JBzD-grpt1lP3b4HpJvrcMgGfdGwwP2jE/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c1","timestamp_ms":1681568331263.914},{"id":"0000000000cb2fb5","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U2CaKYtAF1kbVl2LFiMXcb4_JHJMnJRwrrguxsPvyZ4qOF-8pMq/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c2","timestamp_ms":1681568028212.701},{"id":"0000000000cb21c4","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U1w5IUAys3ZVgu9KriTibhcXkdTvUMSDUq5LObRto_sQkhH95zj/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cada38","timestamp_ms":1681567923189.972},{"id":"0000000000cb295c","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U1zn2FLpZaqb3jSYEhKwS7Dr4lfpHK2Pq2vVF_TE1BpBRd4tqoK/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad086","timestamp_ms":1681567728958.877},{"id":"0000000000cb1913","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U2HHjTk9iGD0hckTy5yKwQQQ80cLL84GIWx8pdvK8H5KbDqXw19/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad7cf","timestamp_ms":1681567410755.49}],"challenge":{"announcements":[],"are_results_final":true,"end_ms":1681581600000,"id":"0000000000c95b94","is_practice_available":true,"result_status":30,"result_status__str":"FINALIZED","start_ms":1681567200000,"tasks":[{"id":"0000000000cad086","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Illumination Optimization"},{"id":"0000000000cad7cf","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Colliding Encoding"},{"id":"0000000000cad9c1","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"Untie"},{"id":"0000000000cad9c2","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"ASCII Art"},{"id":"0000000000cada38","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Rainbow Sort"}],"title":"Round A"}}\n'

In [38]:
df[83:90]['data']

83                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       b'{"attempts":[{"id":"0000000000cb38b1","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U3AfyK3jBCqErmXNP2JBzD-grpt1lP3b4HpJvrcMgGfdGwwP2jE/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c1","timestamp_ms":1681568331263.914},{"id":"0000000000cb2fb5","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U2CaKYtAF1kbVl2LFiMXcb4_JHJMnJRwrrguxsPvyZ4qOF-8pMq/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c2","timestamp_ms":1681568028212.701},{"id":"0000000000cb21c4","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U1w5IUAys3ZVgu9KriTibhcXkdTvUMSDUq5LObRto_sQkhH95zj/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cada38","timestamp_ms":1681567923189.972},{"id":"0000000000cb295c","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U1zn2FLpZaqb3jSYEhKwS7Dr4lfpHK2Pq2vVF_TE1BpBRd4tqoK/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad086","timestamp_ms":1681567728958.877},{"id":"0000000000cb1913","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U2HHjTk9iGD0hckTy5yKwQQQ80cLL84GIWx8pdvK8H5KbDqXw19/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad7cf","timestamp_ms":1681567410755.49}],"challenge":{"announcements":[],"are_results_final":true,"end_ms":1681581600000,"id":"0000000000c95b94","is_practice_available":true,"result_status":30,"result_status__str":"FINALIZED","start_ms":1681567200000,"tasks":[{"id":"0000000000cad086","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Illumination Optimization"},{"id":"0000000000cad7cf","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Colliding Encoding"},{"id":"0000000000cad9c1","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"Untie"},{"id":"0000000000cad9c2","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"ASCII Art"},{"id":"0000000000cada38","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Rainbow Sort"}],"title":"Round A"}}\n'
84                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      b'{"attempts":[{"id":"0000000000cb3ef5","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U3iRoJ7Sswj37W993r4pR_Gu4IbwAoDFRv26MzV7vCk0GdkeEJd/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c1","timestamp_ms":1681568374893.135},{"id":"0000000000cb28be","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U0dyqfh9k7wSOvjjU2kN-kIzDTdhE7gg57RZeuEP5hBt8b9IYXc/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c2","timestamp_ms":1681568017138.691},{"id":"0000000000cb216e","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U2NV03PFNvzVEVPHXCn8wl90nsRrDSskwMlb3fkhhK_Rr8oBA89/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cada38","timestamp_ms":1681567875250.355},{"id":"0000000000cb1ca2","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U1a048B2U0dKGfrhfyGQMR6HU_SI-TCm0jn1CEK6gD1uGDi1Dn8/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad086","timestamp_ms":1681567689616.977},{"id":"0000000000cb18ca","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U2qg0ITw1J33uFoMn3r12342YEGABOp_OBfkK3ZOhHZ6pO-eZ_0/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad7cf","timestamp_ms":1681567462677.401}],"challenge":{"announcements":[],"are_results_final":true,"end_ms":1681581600000,"id":"0000000000c95b94","is_practice_available":true,"result_status":30,"result_status__str":"FINALIZED","start_ms":1681567200000,"tasks":[{"id":"0000000000cad086","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Illumination Optimization"},{"id":"0000000000cad7cf","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Colliding Encoding"},{"id":"0000000000cad9c1","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"Untie"},{"id":"0000000000cad9c2","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"ASCII Art"},{"id":"0000000000cada38","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Rainbow Sort"}],"title":"Round A"}}\n'
85                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      b'{"attempts":[{"id":"0000000000cb3879","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U2IEdWsgyg7ss4VyrC-swCuEL3qiHwyRHFvc1YNzlm6N0Rojntl/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c1","timestamp_ms":1681568555576.118},{"id":"0000000000cb3fb1","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U22CNdNjm_792PuXo82b6gXAlwXJPkKSzSwrQlNnVvrImpsT3kF/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad9c2","timestamp_ms":1681568288563.203},{"id":"0000000000cb2fe9","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U0iq8AOBWACGetvjMjjJwOVOsxyr3ojzdx2oXMDvyJ9FlgS6PQr/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cada38","timestamp_ms":1681568137637.027},{"id":"0000000000cb2919","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U3xOsbTj0t9Fc1-anamtU4enrNuAihmcHBYyTOKesWzi__9wQM7/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad086","timestamp_ms":1681567916345.631},{"id":"0000000000cb0820","is_practice":false,"is_scoring":true,"judgement":{"compilation_output":"","results":[{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"},{"status":1,"status__str":"FINAL","verdict":1,"verdict__str":"CORRECT"}]},"source_file":{"filename":"Solution.cpp","url":"https://codejam.googleapis.com/dashboard/get_file/AQj_6U11thIxwym0mOjqC2r0jc_TL02hnNYka-ukO3Gq_GClRBM3BNY0/Solution.cpp"},"src_language":3,"src_language__str":"CPP","task_id":"0000000000cad7cf","timestamp_ms":1681567538074.344}],"challenge":{"announcements":[],"are_results_final":true,"end_ms":1681581600000,"id":"0000000000c95b94","is_practice_available":true,"result_status":30,"result_status__str":"FINALIZED","start_ms":1681567200000,"tasks":[{"id":"0000000000cad086","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Illumination Optimization"},{"id":"0000000000cad7cf","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Colliding Encoding"},{"id":"0000000000cad9c1","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"Untie"},{"id":"0000000000cad9c2","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":9},{"type":1,"type__str":"VISIBLE","value":20}],"title":"ASCII Art"},{"id":"0000000000cada38","task_type":1,"task_type__str":"CODE_JAM","tests":[{"type":1,"type__str":"VISIBLE","value":0},{"type":1,"type__str":"VISIBLE","value":4},{"type":1,"type__str":"VISIBLE","value":10}],"title":"Rainbow Sort"}],"title":"Round A"}}\n'

In [30]:
df[83]

KeyError: 83